/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;


import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

/**
 *
 * @author Bakhara
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        showDate();
        showTime();
        setTitle("Uangku");
        setIcon();
    }
    
    public DashBoard(String firstName, String lastName){
        initComponents();
        firstNameLabel.setText(firstName);
        lastNameLabel.setText(lastName);
        showDate();
        showTime();
        setTitle("Uangku");
        setIcon();
    }
    
    void showDate(){
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dateLabel.setText(s.format(date));
    }
    
    void showTime(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               Date date = new Date();
               SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
               timeLabel.setText(s.format(date));
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        pemasButton = new javax.swing.JButton();
        pengeButton = new javax.swing.JButton();
        lapButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pemasField = new javax.swing.JTextField();
        pemasSubmitButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pemasKegField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pnlCard2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pengelField = new javax.swing.JTextField();
        pengelSubmitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pengelKegField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pnlCard3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lapPrintButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        pemasButton.setBackground(new java.awt.Color(255, 255, 102));
        pemasButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pemasButton.setText("Pemasukkan");
        pemasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasButtonActionPerformed(evt);
            }
        });

        pengeButton.setBackground(new java.awt.Color(255, 255, 102));
        pengeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pengeButton.setText("Pengeluaran");
        pengeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeButtonActionPerformed(evt);
            }
        });

        lapButton.setBackground(new java.awt.Color(255, 255, 102));
        lapButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lapButton.setText("Laporan");
        lapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapButtonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Uangku.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        firstNameLabel.setText("first Name");

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lastNameLabel.setText("last Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selamat datang");

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setText("12 - 10 - 2012");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeLabel.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pemasButton, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(pengeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lapButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pemasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pengeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCard1.setBackground(new java.awt.Color(0, 204, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEMASUKAN");

        pemasSubmitButton.setBackground(new java.awt.Color(255, 255, 102));
        pemasSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pemasSubmitButton.setText("SUBMIT");
        pemasSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasSubmitButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Input Jumlah Uang");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Input Kegiatan");

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(188, 188, 188))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCard1Layout.createSequentialGroup()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pemasKegField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCard1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pemasField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemasSubmitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasKegField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(pemasSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlCards.add(pnlCard1, "card2");

        pnlCard2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PENGELUARAN");

        pengelSubmitButton.setBackground(new java.awt.Color(255, 255, 102));
        pengelSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pengelSubmitButton.setText("SUBMIT");
        pengelSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengelSubmitButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Input Jumlah Uang");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Input Kegiatan");

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengelSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengelKegField)
                    .addComponent(pengelField)
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengelKegField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengelField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(pengelSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlCards.add(pnlCard2, "card3");

        pnlCard3.setBackground(new java.awt.Color(204, 0, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAPORAN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Kegiatan", "Tanggal", "Waktu", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lapPrintButton.setBackground(new java.awt.Color(255, 255, 102));
        lapPrintButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lapPrintButton.setText("Print");
        lapPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPrintButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(lapPrintButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCard3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lapPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlCards.add(pnlCard3, "card4");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasButtonActionPerformed
       pnlCards.removeAll();
       pnlCards.add(pnlCard1);
       pnlCards.repaint();
       pnlCards.revalidate();
    }//GEN-LAST:event_pemasButtonActionPerformed

    private void pengeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeButtonActionPerformed
       pnlCards.removeAll();
       pnlCards.add(pnlCard2);
       pnlCards.repaint();
       pnlCards.revalidate();
    }//GEN-LAST:event_pengeButtonActionPerformed

    private void lapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapButtonActionPerformed
       pnlCards.removeAll();
       pnlCards.add(pnlCard3);
       pnlCards.repaint();
       pnlCards.revalidate();
    }//GEN-LAST:event_lapButtonActionPerformed

    private void pengelSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengelSubmitButtonActionPerformed
        //ketika data masih ada yang kosong 
        if(pengelField.getText().length() == 0 && pengelKegField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }else if(pengelField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }else if(pengelKegField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }
        
        //ketika semua sudah penuh
        else{
            DashBoard.AddRowToJTable(new Object[] {
                "pengeluaran",
                pengelKegField.getText(),
                dateLabel.getText(),
                timeLabel.getText(),
                pengelField.getText(),
            });
            jLabel6.setText(Integer.toString(getSum()));

            JOptionPane.showMessageDialog(null, "Berhasil di Submit :)");
        }
    }//GEN-LAST:event_pengelSubmitButtonActionPerformed

    private void lapPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPrintButtonActionPerformed
        String path = "";
        
        //nama file
        String nameFile = JOptionPane.showInputDialog("masukkan nama file");
        
        //choose directory
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        
        if(x == JFileChooser.APPROVE_OPTION){
            path = j.getSelectedFile().getPath();
        }
        
        Document doc = new Document();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+ "/" + nameFile + ".pdf"));
            doc.open();
            
            PdfPTable tbl = new PdfPTable(5 );
            Paragraph para = new Paragraph();
           
            //
            Font catFont = new Font(null, 18, Font.BOLD);
            //title setting
            para.add(new Paragraph("Laporan Keuangan", catFont));
            para.add(new Paragraph(" "));
            para.add(new Paragraph("Nama User   : " + firstNameLabel.getText() + " " + lastNameLabel.getText()));
            para.add(new Paragraph(" "));
            para.add(new Paragraph("Saldo Akhir   : " + getSum()));
            para.add(new Paragraph(" "));
            if( getSum() > 0){
                para.add(new Paragraph("Keren kamu bisa mensisihkan uangmu :)"));
                para.add(new Paragraph(" "));
            }else if(getSum() < 0){
                para.add(new Paragraph("Ayo dong kamu harus bisa nabung, semangat ya !"));
                para.add(new Paragraph(" "));
            }
            
            //table setting
            //adding header
            tbl.addCell("Type");
            tbl.addCell("Kegiatan");
            tbl.addCell("Tanggal");
            tbl.addCell("Waktu");
            tbl.addCell("Jumlah");
            
            for(int i = 0; i < jTable1.getRowCount(); i++){
                String type = jTable1.getValueAt(i, 0).toString();
                String keg = jTable1.getValueAt(i, 1).toString();
                String tanggal = jTable1.getValueAt(i, 2).toString();
                String waktu = jTable1.getValueAt(i, 3).toString();
                String jumlah = jTable1.getValueAt(i, 4).toString();
                
                tbl.addCell(type);
                tbl.addCell(keg);
                tbl.addCell(tanggal);
                tbl.addCell(waktu);
                tbl.addCell(jumlah);
            }
            
            doc.add(para);
            doc.add(tbl);
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        doc.close();
        
        JOptionPane.showMessageDialog(null, "Berhasil di Save :)");
    }//GEN-LAST:event_lapPrintButtonActionPerformed

    private void pemasSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasSubmitButtonActionPerformed
        //ketika data masih ada yang kosong 
        if(pemasField.getText().length() == 0 && pemasKegField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }else if(pemasField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }else if(pemasKegField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Mohon diisi semua datanya ya :)");
        }
        
        //ketika semua sudah penuh
        else{
            DashBoard.AddRowToJTable(new Object[] {
                "pemasukan",
                pemasKegField.getText(),
                dateLabel.getText(),
                timeLabel.getText(),
                pemasField.getText(),
            });
            jLabel6.setText(Integer.toString(getSum()));
            
            JOptionPane.showMessageDialog(null, "Berhasil di Submit :)");
        }
    }//GEN-LAST:event_pemasSubmitButtonActionPerformed

    public int getSum(){
        int intTableRow = jTable1.getRowCount();
        int sum = 0;
        for(int i = 0; i < intTableRow; i++){
            //pengurangan
            if(jTable1.getValueAt(i, 0).toString().equals("pengeluaran")){
                sum = sum - Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }
            //pemasukan
            else if(jTable1.getValueAt(i, 0).toString().equals("pemasukan")){
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }
        }
        return sum;
    }
    /**
     * @param args the command line arguments
     */
    public static void AddRowToJTable(Object[] dataRow){
        DefaultTableModel model;
        model = (DefaultTableModel)jTable1.getModel();
        model.addRow(dataRow);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JButton lapButton;
    private javax.swing.JButton lapPrintButton;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton pemasButton;
    private javax.swing.JTextField pemasField;
    private javax.swing.JTextField pemasKegField;
    private javax.swing.JButton pemasSubmitButton;
    private javax.swing.JButton pengeButton;
    private javax.swing.JTextField pengelField;
    private javax.swing.JTextField pengelKegField;
    private javax.swing.JButton pengelSubmitButton;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
